import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/context/Providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans", // 🔥 clave
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
        <body className="min-h-full flex flex-col">
          <Providers>
            {children}
          </Providers>
        </body>
    </html>
  );
}
